Let's consider the simplest one-layer neural network, with input x, parameters/weights w and b, and soem loss function. 

In [2]:
import torch

In [14]:
x = torch.ones(5) # input tensor
y = torch.zeros(3) # expected output
w = torch.randn(5, 3, requires_grad=True) # requires grad here, cause we'll be optimizing these parameters
b = torch.randn(3, requires_grad=True) # requires grad here, cause we'll be optimizing these parameters
z = torch.matmul(x, w)+b
loss = torch.nn.functional.binary_cross_entropy_with_logits(z, y)

In [15]:
print(f"Gradient function for z = {z.grad_fn}")
print(f"Gradient function for loss = {loss.grad_fn}")

Gradient function for z = <AddBackward0 object at 0x7f9e8c9443d0>
Gradient function for loss = <BinaryCrossEntropyWithLogitsBackward object at 0x7f9e8c7b1fd0>


### Computing gradients

In [17]:
print(w)
print(b)
print(loss)
print(z)

tensor([[-0.7537,  0.2388, -0.2960],
        [ 0.1549, -1.3275,  1.7987],
        [ 0.0607,  1.6378,  2.1302],
        [ 0.2651,  0.7695, -0.1092],
        [-0.7626,  1.0868,  0.0937]], requires_grad=True)
tensor([ 0.7000, -0.1423, -1.3882], requires_grad=True)
tensor(1.7443, grad_fn=<BinaryCrossEntropyWithLogitsBackward>)
tensor([-0.3356,  2.2630,  2.2292], grad_fn=<AddBackward0>)


In [16]:
loss.backward()
print(w.grad)
print(b.grad)

tensor([[0.1390, 0.3019, 0.3009],
        [0.1390, 0.3019, 0.3009],
        [0.1390, 0.3019, 0.3009],
        [0.1390, 0.3019, 0.3009],
        [0.1390, 0.3019, 0.3009]])
tensor([0.1390, 0.3019, 0.3009])
