In [1]:
import torch
from torch.autograd import grad
import torch.nn.functional as F

In [2]:
torch.cuda.is_available()

True

In [3]:
torch.cuda.get_device_name()

'NVIDIA GeForce RTX 3080'

#### Let's define the sample function from notes.

In [4]:
x = torch.tensor([3.])
w = torch.tensor([2.], requires_grad=True)
b = torch.tensor([1.], requires_grad=True)
a = F.relu(x*w + b)

In [5]:
a

tensor([7.], grad_fn=<ReluBackward0>)

#### Let's compute the derivitave of a with respect to w (retain means keep computation graph in memory):

In [6]:
grad(a, w, retain_graph=True)

(tensor([3.]),)

In [7]:
grad(a, b)

(tensor([1.]),)